// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The offlinecv Authors

/**
 * Byte-identical extraction gate for the export-projection split (#442, Stage A).
 *
 * `to-json-resume.ts` used to walk the render model's `sections[].entries[]`
 * directly; it now drives off `projectAtsExport(model)`. This is a PURE
 * extraction — the JSON-Resume output must be unchanged. Two proofs here:
 *
 *   1. A hand-authored golden JsonResume (NOT generated by the code under test)
 *      pins the exact `toJsonResume` output for a model covering every mapped
 *      section kind — so any drift in the mapping is a hard failure. (The
 *      section-by-section value assertions in `to-json-resume.test.ts` pin the
 *      same output from the other direction.)
 *   2. `projectAtsExport` preserves every `fields` object and `bullets` array by
 *      REFERENCE, per entry, in flattened document order, tagged by section kind
 *      — and carries none of the render model's layout hints.
 */

import { readFileSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, it, expect } from "vitest";
import { toJsonResume, JSON_RESUME_SCHEMA } from "./to-json-resume.ts";
import {
  projectAtsExport,
  type AtsExportProjection,
} from "./ats-export-projection.ts";
import type { AtsResumeModel } from "./ats-resume-model.ts";
import { buildAtsResumeModel } from "./ats-resume-model.ts";
import { runCascade } from "../heuristics/cascade.ts";
import { computeAnonymousAtsScore } from "../score/score.ts";
import { APP_VERSION } from "../version.ts";

// A model exercising every export-mapped section kind, plus layout hints
// (headerLine/subLine/dates/atomicSegments/headerBold) that MUST be dropped.
const MODEL: AtsResumeModel = {
  contact: {
    name: "Jane Candidate",
    headline: "Staff Engineer", // display-only — never in JSON Resume
    email: "jane@example.com",
    phone: "(312) 555-0123",
    location: "Chicago, IL, USA",
    links: ["linkedin.com/in/jane"],
    linkHrefs: ["https://linkedin.com/in/jane"],
    profiles: [
      { url: "https://linkedin.com/in/jane", network: "LinkedIn", kind: "social" },
      { url: "https://github.com/JaneC", network: "GitHub", kind: "code" },
    ],
  },
  summary: "A summary.",
  summaryHeading: "Summary",
  sections: [
    {
      heading: "Experience",
      kind: "experience",
      entries: [
        {
          headerLine: "Senior Engineer · Acme Corp",
          headerLineDate: "Jan 2020 – March 2022",
          headerBold: true,
          bullets: ["Shipped X", "Led Y"],
          fields: {
            organization: "Acme Corp",
            position: "Senior Engineer",
            startDate: "Jan 2020",
            endDate: "March 2022",
          },
        },
        {
          headerLine: "Engineer · Startup Inc",
          bullets: [],
          fields: {
            organization: "Startup Inc",
            position: "Engineer",
            startDate: "2022",
            isCurrent: true,
            endDate: "2099", // dropped because isCurrent
          },
        },
      ],
    },
    {
      heading: "Projects",
      kind: "projects",
      entries: [
        {
          headerLine: "Cool Project",
          bullets: ["Built a thing"],
          fields: {
            organization: "Cool Project",
            url: "https://github.com/JaneC/cool",
            startDate: "Summer 2021",
          },
        },
      ],
    },
    {
      heading: "Achievements",
      kind: "achievements",
      entries: [
        {
          headerLine: "Patent US1234 · 2021",
          headerBold: false,
          bullets: [],
          fields: { title: "Patent US1234", startDate: "2021" },
        },
      ],
    },
    {
      heading: "Education",
      kind: "education",
      entries: [
        {
          headerLine: "B.S., Computer Science",
          subLine: "State University",
          bullets: ["Coursework: Algorithms, Databases"],
          fields: {
            organization: "State University",
            studyType: "B.S.",
            area: "Computer Science",
            endDate: "2019",
            courses: ["Algorithms", "Databases"],
          },
        },
      ],
    },
    {
      heading: "Skills",
      kind: "skills",
      entries: [
        {
          headerLine: "TypeScript · React · Node.js",
          bullets: [],
          atomicSegments: true,
          headerBold: false,
          fields: { skills: ["TypeScript", "React", "Node.js"] },
        },
      ],
    },
  ],
};

// Hand-authored expected output — the byte-identical golden. Deliberately NOT
// derived from the code under test.
const EXPECTED = {
  $schema: JSON_RESUME_SCHEMA,
  basics: {
    name: "Jane Candidate",
    email: "jane@example.com",
    phone: "(312) 555-0123",
    url: undefined,
    location: { city: "Chicago", region: "IL", countryCode: "US" },
    profiles: [
      { network: "LinkedIn", url: "https://linkedin.com/in/jane", username: "jane" },
      { network: "GitHub", url: "https://github.com/JaneC", username: "JaneC" },
    ],
  },
  work: [
    {
      name: "Acme Corp",
      position: "Senior Engineer",
      startDate: "2020-01",
      endDate: "2022-03",
      highlights: ["Shipped X", "Led Y"],
    },
    {
      name: "Startup Inc",
      position: "Engineer",
      startDate: "2022",
      endDate: undefined,
      highlights: undefined,
    },
  ],
  education: [
    {
      institution: "State University",
      area: "Computer Science",
      studyType: "B.S.",
      startDate: undefined,
      endDate: "2019",
      courses: ["Algorithms", "Databases"],
    },
  ],
  skills: [{ name: "TypeScript" }, { name: "React" }, { name: "Node.js" }],
  projects: [
    {
      name: "Cool Project",
      url: "https://github.com/JaneC/cool",
      startDate: "Summer 2021",
      endDate: undefined,
      highlights: ["Built a thing"],
    },
  ],
  awards: [{ title: "Patent US1234", date: "2021" }],
  meta: { version: APP_VERSION },
};

/** The extraction's core faithfulness property: `projectAtsExport` carries
 *  every entry's `fields` object and `bullets` array through BY REFERENCE, per
 *  entry, in flattened document order. Since `to-json-resume`'s mappers are
 *  unchanged, identical inputs ⇒ identical JSON-Resume output — this is what
 *  makes the split byte-identical. */
function expectPreservesRefs(
  model: AtsResumeModel,
  projection: AtsExportProjection,
) {
  const flat = model.sections.flatMap((s) => s.entries);
  expect(projection.entries).toHaveLength(flat.length);
  projection.entries.forEach((projected, i) => {
    expect(projected.fields).toBe(flat[i].fields);
    expect(projected.bullets).toBe(flat[i].bullets);
  });
}

describe("toJsonResume — byte-identical after export-projection split (#442)", () => {
  it("matches the hand-authored golden for every section kind", () => {
    expect(toJsonResume(MODEL)).toEqual(EXPECTED);
  });

  it("serializes byte-identically to the golden's serialization", () => {
    expect(JSON.stringify(toJsonResume(MODEL))).toBe(JSON.stringify(EXPECTED));
  });
});

describe("projectAtsExport — faithful, layout-free extraction (#442)", () => {
  const projection: AtsExportProjection = projectAtsExport(MODEL);

  it("carries the model's contact through unchanged (by reference)", () => {
    expect(projection.contact).toBe(MODEL.contact);
  });

  it("flattens sections into document-order entries tagged by kind", () => {
    expect(projection.entries.map((e) => e.kind)).toEqual([
      "experience",
      "experience",
      "projects",
      "achievements",
      "education",
      "skills",
    ]);
  });

  it("preserves every fields object and bullets array by reference, in order", () => {
    expectPreservesRefs(MODEL, projection);
  });

  it("carries ONLY kind/fields/bullets — no layout hints leak through", () => {
    for (const entry of projection.entries) {
      expect(Object.keys(entry).sort()).toEqual(["bullets", "fields", "kind"]);
    }
  });
});

// ── Corpus proof: every real parsed model projects faithfully (#442 gate) ──────
//
// #442's acceptance is "byte-identical on the fixture corpus". The mechanism is
// projection faithfulness: `expectPreservesRefs` asserts the projection feeds
// the (unchanged) mappers the exact same `fields`/`bullets` the old direct walk
// did — so `toJsonResume` output cannot change. Run it over the WHOLE fixture
// corpus (synthetic personas only — see tests/fixtures/pdfs/README.md), not one
// fixture, so any layout-shape that projects wrong is caught.

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURE_ROOT = join(HERE, "../../..", "tests/fixtures/pdfs");

function walkPdfs(dir: string): string[] {
  const out: string[] = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walkPdfs(p));
    else if (e.isFile() && e.name.toLowerCase().endsWith(".pdf")) out.push(p);
  }
  return out.sort();
}

describe("projectAtsExport — corpus parity (synthetic personas)", { timeout: 20000 }, () => {
  const fixtures = walkPdfs(FIXTURE_ROOT);

  it("finds fixtures to project", () => {
    expect(fixtures.length).toBeGreaterThan(0);
  });

  for (const fixture of fixtures) {
    const name = fixture.slice(FIXTURE_ROOT.length + 1);
    it(`projects faithfully: ${name}`, async () => {
      const cascade = await runCascade(new Uint8Array(readFileSync(fixture)));
      const score = computeAnonymousAtsScore({
        parsed: { ...cascade.canonical.fields },
        fieldConfidence: cascade.canonical.fieldConfidence,
        triggers: cascade.triggers,
        rawText: cascade.rawText,
        sections: cascade.canonical.sections,
      });
      const model = buildAtsResumeModel(cascade, score);

      expectPreservesRefs(model, projectAtsExport(model));
      // And the JSON Resume built via the projection is well-formed.
      expect(toJsonResume(model).$schema).toBe(JSON_RESUME_SCHEMA);
    });
  }
});
